# toy_en_de.yaml

# Vocabulary files that were just created
src_vocab: /storage/HopfieldNMT/toy-ende/run/example.vocab.src
tgt_vocab: /storage/HopfieldNMT/toy-ende/run/example.vocab.tgt

# Where to save the checkpoints
save_model: /storage/HopfieldNMT/toy-ende/run/hopfield/

save_checkpoint_steps: 500
keep_checkpoint: 10
seed: 3435
train_steps: 2000
valid_steps: 1000
warmup_steps: 1000
report_every: 100

decoder_type: hopfield
encoder_type: hopfield
word_vec_size: 512
hidden_size: 512
layers: 6
transformer_ff: 2048
heads: 8

accum_count: 2
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 2.0
max_grad_norm: 0.0

batch_type: "tokens"
batch_size: 1024
dropout: 0.1
label_smoothing: 0.1

data:
    corpus_1:
        path_src: /storage/HopfieldNMT/toy-ende/src-train.txt
        path_tgt: /storage/HopfieldNMT/toy-ende/tgt-train.txt
    valid:
        path_src: /storage/HopfieldNMT/toy-ende/src-val.txt
        path_tgt: /storage/HopfieldNMT/toy-ende/tgt-val.txt

param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'
share_decoder_embeddings: true
share_embeddings: true
