
## Where the samples will be written
save_data: /storage/HopfieldNMT/toy-ende/run/example
## Where the vocab(s) will be written
src_vocab: /storage/HopfieldNMT/toy-ende/run/example.vocab.src
tgt_vocab: /storage/HopfieldNMT/toy-ende/run/example.vocab.tgt
# Prevent overwriting existing files in the folder
overwrite: False

# Corpus opts:
data:
    corpus_1:
        path_src: /storage/HopfieldNMT/toy-ende/src-train.txt
        path_tgt: /storage/HopfieldNMT/toy-ende/tgt-train.txt
    valid:
        path_src: /storage/HopfieldNMT/toy-ende/src-val.txt
        path_tgt: /storage/HopfieldNMT/toy-ende/tgt-val.txt
